on: push

name: Test

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11
        ports: ['5432:5432']
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        uses: ruby/setup-ruby@v1.64.4
      with:
        ruby-version: 2.5.2

      - name: Install Dependencies
        run: |
          sudo apt install -yqq libpq-dev
          gem intall bundler

      - name: Install Gems
        run: |
          bundle install

      - name: Prepare Database
        run: |
          bundle exec rails db:prepare

      - name: Run Tests
        env:
          DATABASE_URL: postgres://postgres:@localhost:5432/congo_test
        run: |
          bundle exec rails test
