on: push

name: Test

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        ports: ['5432:5432']
        env:
          POSTGRES_PASSWORD: password
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5

    steps:
      - name: Checkout
      - uses: actions/checkout@v2

      - name: Setup
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.5
      - name: Bundle
      - run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Run Tests
        env:
          DB_NAME: postgres
          DB_USERNAME: postgres
          DB_PASSWORD: password
          RAILS_ENV: test
          run: |
            cp config/application.example.yml config/application.yml
            bin/rails db:setup
            bin/rails test
